@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractCollection <|- asavbasd
AbstractList <|-- ArrayList
AbstractList <|-- Asbv

class ArrayList {
Object[] elementData
size()
}

class Asbv {
Object[] elementData
size()
}

enum Operators {
exterior derivative
wedge
}

@enduml